# Installing a base image
FROM alpine:latest

# Install fortune
RUN apk add fortune

# Print out description 
RUN echo "Fortune is a program that prints out silly quotes."

# Run the fortune command
CMD [ "fortune" ]